#!/bin/bash
jupyter serverextension enable --py nbzip --sys-prefix --user
jupyter nbextension install --py nbzip --user
jupyter nbextension enable --py nbzip --user
jupyter serverextension enable nbgitpuller --sys-prefix --user
#jupyter contrib nbextension install --user

#cp preStop.sh /home/jovyan
cp utilities/jupyter_notebook_config.py ~/.jupyter/
